version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1-bionic
    restart: always
    ports:
      - "27018:27017"
    networks:
      - backend
  app:
    container_name: master-app
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment: 
      - MONGODB_URL=mongodb+srv://bpechaz:TcwhnSYmEMgocIEb@clustertest.vj2k80h.mongodb.net/?retryWrites=true&w=majority
      - CLIENT_URL=${CLIENT_URL}
    links: 
      - mongo  
    depends_on:
      - mongo  
    networks:
      - backend

networks:
  backend:
    driver: bridge    
